FROM alpine:3.8
RUN apk add --no-cache bash python3 python3-dev openssl-dev libffi-dev py3-pip alpine-sdk
RUN pip3 install pip --upgrade && pip3 install wheel

WORKDIR /kama
COPY . .
#RUN python3 -m grpc_tools.protoc -Iprotos --python_out=kama --grpc_python_out=kama protos/kama.proto
RUN pip3 wheel -w wheels .
