FROM alpine:3.8
RUN apk add --no-cache bash python3 python3-dev openssl-dev libffi-dev py3-pip alpine-sdk
RUN pip3 install pip --upgrade
RUN pip3 install grpcio
RUN pip3 install nose

WORKDIR /kama
COPY . .
RUN pip3 install .
